export const GET_EPISODES = "GET_EPISODES";
export const DELETE_EPISODE = "DELETE_EPISODE";
export const ADD_EPISODE = "ADD_EPISODE";
export const UPDATE_EPISODE = "UPDATE_EPISODE";

export const GET_EPISODES_REQUEST_START = "GET_EPISODES_REQUEST_START";
